# Generated by Django 3.1.5 on 2021-01-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('email', models.EmailField(max_length=30)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=100)),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
