# Generated by Django 3.1.5 on 2021-01-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20210107_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='favourite',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
