# Generated by Django 3.1.5 on 2021-01-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite',
            field=models.CharField(auto_created=True, default='', max_length=255),
        ),
    ]
