# Generated by Django 3.1.5 on 2021-01-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0010_auto_20210107_2113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
